### ISSUE TITLE
Application element within the library Manifest creates conflict with consumer app

### ISSUE THREAD

**Issue by elhanan-mishraky** [nanorepsdk/AndroidWidgetApp#29]
Hey team,

It seems that the next element prevents me from being able to use the nanorepsdk:

<application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true">
</application>

The Android compiler says that I cannot set android:allowBackup="false" or define android:label because of the configuration in the nanorepsdk.

Is it possible to remove the application element from nanorepsdk Manifest?

**Comment by noatul** [comment]
removed.
try: compile 'com.nanorep:nanowidget:1.3.9'

**Comment by elhanan-mishraky** [comment]
Thanks!
